### ISSUE TITLE
webview.html does not the play video

### ISSUE THREAD

**Issue by ichit** [Th3R3alDuk3/BigBlueButtonDownloader#1]
Hi,
Thanks for your effort to make available the means to download and play BigBlueButton video offline. I used the instructions given and downloaded both videos (deskshare.webm and webcams.webm) into a folder, but when i play the webview.html it opens on the browser but the video does not play.
Kindly assist me to solve these problem.
kind regards

**Comment by Th3R3alDuk3** [comment]
Hey, what is the file extension of your video files? Could you open the videos seperately with for example media player?

**Comment by Th3R3alDuk3** [comment]
You can press F12 in your browser and look for error messages in the console or sources tab. Otherwise send me the link and ill test.

**Comment by Th3R3alDuk3** [comment]
which browser?

**Comment by Th3R3alDuk3** [comment]
which browser?

**Comment by ichit** [comment]
Hi, sorry for replying a bit late. I have tested the downloader on Debian Linux OS, and it works very fine like a miracle when i played the webview.html. Thanks for your work. You have save a soul tons of hours of hard-work. I previously had the problem of playing on my windows 10. But it does not matter now anymore, i will be using my Linux OS to play the files. Thanks a lot.

**Comment by ichit** [comment]
> You can press F12 (Ctrl+ Shift + I) in your browser and look for error messages in the console or sources tab. Otherwise send me the link and ill tFailed to load resource: net::ERR_FILE_NOT_FOUND
webcams.mp4:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
deskshare.mkv:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
webcams.mkv:1 Failed to lo

**Comment by ichit** [comment]
> You can press F12 (Ctrl+ Shift + I) in your browser and look for error messages in the console or sources tab. Otherwise send me the link and ill test.

deskshare.mp4:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
webcams.mp4:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
deskshare.mkv:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
webcams.mkv:1 Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by Th3R3alDuk3** [comment]
oh thanks i can see the error

**Comment by Th3R3alDuk3** [comment]
seems like.ure.using an older version. git pull and retry

**Comment by micschwarz** [comment]
Maybe you should create a new release and link to that in the README. I ran into the same issue :)

**Comment by Th3R3alDuk3** [comment]
Hmmm I already did. The displayed release file date is not correct. Is it possiblie to share the bbb link of your video session for testing?

**Comment by micschwarz** [comment]
Sry, this is not possible. I did download the release linked in the readme and it did not work (Same mkv-file error as mentioned here). The current file in the repo works fine

**Comment by Th3R3alDuk3** [comment]
Ah okay thanks a lot! Updating the same release file seems to fail for version 1.2. I'll fix that today. Thanks!!!

**Comment by Th3R3alDuk3** [comment]
Should be solved :P

**Comment by Th3R3alDuk3** [comment]
Should be solved!
